Events
The-Fathers-House-Church/tfh-backend pull request #2
Opened 2023-01-16 11:46 UTC by darmhoo

View all event
Create Event
View one event

2023-01-16 15:44 UTC, Golden-Ogbeka requested changes
- There are some traces of devotional inside the event controllers
- The event date isn't unique. One date can have multiple events. The check for a unique date in add event isn't required 
- The extra fields for date or number limit in events isn't required from the frontend. The validation makes them required by default. They should be added only if the frontend sends them not compulsorily

2023-01-16 15:50 UTC, Golden-Ogbeka commented
Does Tern JS provide the language and coding support of Typescript for Javascript files?

2023-01-16 17:52 UTC, darmhoo commented
I don't understand the third comment. I didn't include the validation in the route file because they are not compulsory

2023-01-16 17:53 UTC, darmhoo commented on api/v1/routes/event.ts
> +        body('allowRegistration', 'Allow Registration is required').trim().exists().isBoolean().withMessage("Allow Registration must be boolean"),
Do you mean this part

2023-01-16 17:53 UTC, darmhoo commented on api/v1/routes/event.ts
> +        body('allowRegistration', 'Allow Registration is required').trim().exists().isBoolean().withMessage("Allow Registration must be boolean"),
@Golden-Ogbeka

2023-01-16 18:23 UTC, Golden-Ogbeka commented on api/v1/routes/event.ts
> +        body('allowRegistration', 'Allow Registration is required').trim().exists().isBoolean().withMessage("Allow Registration must be boolean"),
Yeah, the .exists means it is required

2023-01-16 18:24 UTC, Golden-Ogbeka commented on api/v1/routes/event.ts
> +        body('allowRegistration', 'Allow Registration is required').trim().exists().isBoolean().withMessage("Allow Registration must be boolean"),
@darmhoo if you try testing the routes without those fields, it shouldnt go through

2023-01-17 07:58 UTC, darmhoo commented on api/v1/routes/event.ts
> +        body('allowRegistration', 'Allow Registration is required').trim().exists().isBoolean().withMessage("Allow Registration must be boolean"),
Ok. i will fix now

2023-01-17 08:48 UTC, Golden-Ogbeka commented
@darmhoo you pushed for theme and main text but we'll proceed with this so testing can begin. Later on, we'll change it for fields that arent compulsort

2023-01-17 08:49 UTC, Golden-Ogbeka approved these changes

2023-01-17 09:15 UTC, merged