Events
The-Fathers-House-Church/tfh-backend pull request #6
Opened 2023-01-21 12:36 UTC by darmhoo

Upload event gallery done

2023-01-21 21:50 UTC, Golden-Ogbeka requested changes
@darmhoo when uploading images, I noticed it's the file path of the image that is being saved not the cloudinary link.
When is the image uploaded to cloudinary.
I didn't see the parser function in use in the route

2023-01-22 04:18 UTC, darmhoo commented on functions/cloudinary.ts
> +const cloudStorage = new CloudinaryStorage({
This is the file responsible for the uploads. it serves as a middleware to check the validity of files sent and also uploads at the same time.

2023-01-22 04:18 UTC, darmhoo commented on api/v1/routes/event.ts
> +router.post('/:id/upload', [parser.array('images'), header('x-api-key', 'API Access Denied')
the parser is doing the job in the routes

2023-01-22 04:18 UTC, darmhoo commented on api/v1/controllers/event.ts
> +                event.gallery.push(fileArray[i].path)
It is the cloudinary link. 
`"https://res.cloudinary.com/dizmz1ylh/image/upload/v1674304347/demo/ds91q1gdyzulbkobjflj.jpg",
            "https://res.cloudinary.com/dizmz1ylh/image/upload/v1674304347/demo/dwoazsj0fwzkgpsteptr.jpg",
            "https://res.cloudinary.com/dizmz1ylh/image/upload/v1674304347/demo/ubqrjy0fi8l9fciw9jxb.jpg"`

2023-01-22 04:19 UTC, darmhoo commented on api/v1/controllers/event.ts
> +                event.gallery.push(fileArray[i].path)
I uploaded those 3 with the api

2023-01-22 07:38 UTC, Golden-Ogbeka commented on api/v1/controllers/event.ts
> +                event.gallery.push(fileArray[i].path)
Ohh interesting. Glad it works

2023-01-22 07:41 UTC, Golden-Ogbeka commented
I missed the Middleware. Maybe it's because parser is also in the controllers but I didn't see it used there

2023-01-22 07:42 UTC, Golden-Ogbeka approved these changes

2023-01-22 16:10 UTC, merged